name: Test Windows Dual Build

on:
  workflow_dispatch

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        arch: [x64, arm64]

    steps:

      - uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Enable Windows
        run: flutter config --enable-windows-desktop

      - name: Build Windows
        run: flutter build windows --debug --target-platform windows-${{ matrix.arch }}

      - name: Show output
        run: dir build/windows
