name: Windows Build

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        arch: [x64, arm64]

    steps:

      - uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Flutter Doctor
        run: flutter doctor -v
        shell: cmd

      - name: Enable Windows
        run: flutter config --enable-windows-desktop
        shell: cmd

      - name: Build Windows
        run: flutter build windows --release --target-platform windows-${{ matrix.arch }}
        shell: cmd

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-${{ matrix.arch }}
          path: build/windows/${{ matrix.arch }}/runner/Release
